# Generated by Django 4.2.10 on 2024-02-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_register_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditem', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='foodimage')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.department')),
            ],
        ),
    ]
